### create diet
POST http://localhost:3000/diet/2023/7/1/breakfast
Content-Type: application/json

{
    "foodName": "제육볶음",
    "foodAmount": 1,
    "hour": 12,
    "min": 30,
    "place": "here",
    "impression": "맛있네",
    "have": false
}

### get diet
GET http://localhost:3000/diet/9
Content-Type: application/json