### signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
"userName": "test2",
"password": "password",
"birth": "2023-06-26T08:26:47.350Z",
"admin": true
}

### sigin

POST http://localhost:3000/auth/signin
Content-Type: application/json

{
"userName": "test2",
"password": "password"
}